# Generated by Django 3.1 on 2020-09-01 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='Dni')),
                ('fecha_registo', models.DateField(default=datetime.datetime.now, verbose_name='fecha de registro')),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
                ('edad', models.PositiveIntegerField(default=0)),
                ('salario', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('estado', models.BooleanField(default=True)),
                ('avatar', models.ImageField(upload_to='avatar/%Y/%m/%d')),
                ('cv', models.FileField(upload_to='cv/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'Empelado',
                'ordering': ['id'],
            },
        ),
    ]
