# Generated by Django 3.1 on 2020-09-02 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiṕo_empleado', models.CharField(max_length=100, verbose_name='Tipo Empleado')),
            ],
            options={
                'verbose_name': 'Tipo Empelado',
                'verbose_name_plural': 'Tipo Empleado',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_empleado',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='erp.tipoempleado'),
            preserve_default=False,
        ),
    ]
